/**
 * @file 员工持久化、岗位策略与课程覆盖注入
 * @author qiuye <yjk150@qq.com>
 * @date 2026-08-31
 * @version 1.1.0
 * @category AgentLoop
 * @algo role-policy-composition
 */
import { invoke } from "@tauri-apps/api/core";
import { buildAgencyShortPersona, ensureAgencyRolePrompt, getAgencyRole, buildRoleAgencyPack } from "../office/agencyRoles";
import { resolveLegacyAgencyRoleId } from "../office/agencyRoleIdMap";
import { nextSnowflakeId, isSnowflakeId } from "./snowflake";
import {
  generateVirtualPersona,
  looksAutoGeneratedName,
  type VirtualPersona,
} from "./virtualEmployeePersona";
import {
  ideOpenPolicyLine,
  readCodingSurfacePrefs,
  type CodeEditorSurface,
} from "./codingSurfacePrefs";
import { loadRoleVoiceBind, saveRoleVoiceBind } from "./voiceRolePrefs";

export type EmployeeStatus = "idle" | "working" | "meeting" | "away";
export type DriveMode = "off" | "sdk" | "input_control";
export type Gender = "male" | "female";
export type RoleKind = "worker" | "reviewer" | "boss";
export type BrainSlot = "command" | "work" | "code";

export interface AvatarStyle {
  id: string;
  name: string;
  skin: string;
  shirt: string;
  accent: string;
}

export const AVATAR_STYLES: AvatarStyle[] = [
  { id: "classic", name: "经典蓝", skin: "#e8c4a8", shirt: "#3d6b8c", accent: "#2a4d66" },
  { id: "warm", name: "暖橙", skin: "#f0c9a8", shirt: "#c45c34", accent: "#8a3a20" },
  { id: "mint", name: "薄荷绿", skin: "#e6cbb0", shirt: "#3d8f7a", accent: "#245c4e" },
  { id: "ink", name: "墨黑", skin: "#d9b396", shirt: "#2f343a", accent: "#111418" },
  { id: "violet", name: "紫霞", skin: "#ebc6b4", shirt: "#6b5b95", accent: "#44386a" },
  { id: "sand", name: "沙褐", skin: "#e2b896", shirt: "#a67c52", accent: "#6e4f32" },
  { id: "sky", name: "晴空", skin: "#f2d2ba", shirt: "#4a90c4", accent: "#2d5f86" },
  { id: "rose", name: "玫瑰", skin: "#ecc0b4", shirt: "#b85c6e", accent: "#7a3544" },
  { id: "nova", name: "星辉", skin: "#e8c8b0", shirt: "#5b8def", accent: "#2f4f9e" },
  { id: "ember", name: "烬红", skin: "#f0c4a4", shirt: "#d9480f", accent: "#8c2a0a" },
  { id: "jade", name: "青玉", skin: "#e4cbb0", shirt: "#0f9f7a", accent: "#0a5c48" },
  { id: "slate", name: "岩灰", skin: "#dcc4a8", shirt: "#64748b", accent: "#334155" },
];

export interface Employee {
  id: string;
  /** Human-facing employee number, e.g. F0001 */
  employeeNo: string;
  /** Fictional display name */
  name: string;
  /** Fictional age for UI */
  age: number;
  role: string;
  avatarId: string;
  deskIndex: number | null;
  status: EmployeeStatus;
  createdAt: number;
  workspaceRoot: string | null;
  readExtraPaths: string[];
  allowNetworkExfil: boolean;
  driveMode: DriveMode;
  gender: Gender;
  roleKind: RoleKind;
  brainSlot: BrainSlot;
  outfit: string;
  hairStyle: string;
  /** Agency catalog role snowflake id */
  agentRoleId: string;
  aiModel: string;
  aiBaseUrl: string;
  aiVisionModel: string;
  apiSource: "inherit" | "local" | "remote";
  /** Empty = use default remote preset from settings */
  remotePresetId: string;
  /** inherit | builtin | external — how Agent opens code files */
  codeEditorSurface: CodeEditorSurface;
  /** 可选：绑定语气 id（如 female-jiazi）；持久化见 voiceRolePrefs */
  voiceToneId?: string;
  /** 可选：TTS 引擎提示 */
  ttsProviderHint?: "auto" | "sherpa-onnx" | "cosyvoice";
}

export interface EmployeeInput {
  name?: string;
  age?: number;
  role: string;
  avatarId: string;
  deskIndex: number | null;
  workspaceRoot?: string | null;
  readExtraPaths?: string[];
  allowNetworkExfil?: boolean;
  driveMode?: DriveMode;
  gender?: Gender;
  roleKind?: RoleKind;
  brainSlot?: BrainSlot;
  outfit?: string;
  hairStyle?: string;
  agentRoleId?: string;
  aiModel?: string;
  aiBaseUrl?: string;
  aiVisionModel?: string;
  employeeNo?: string;
  apiSource?: "inherit" | "local" | "remote";
  remotePresetId?: string;
  codeEditorSurface?: CodeEditorSurface;
}

interface EmployeeRowDto {
  id: string;
  name: string;
  role: string;
  avatarId: string;
  deskIndex: number | null;
  status: string;
  createdAt: number;
  workspaceRoot: string | null;
  readExtraPaths: string;
  allowNetworkExfil: boolean;
  driveMode: string;
  gender: string;
  roleKind: string;
  brainSlot: string;
  outfit?: string;
  hairStyle?: string;
  agentRoleId?: string;
  aiModel?: string;
  aiBaseUrl?: string;
  aiVisionModel?: string;
  employeeNo?: string;
  apiSource?: string;
  remotePresetId?: string;
  age?: number;
  codeEditorSurface?: string;
}

const STORAGE_KEY = "xu.aiEmployees";
const PROJECTS_DB_KEY = "projects_list";
const MIGRATION_KEY = "xu.employee_schema_v2";
let cache: Employee[] = [];
let bootstrapped = false;

function needsLegacyIdMigration(id: string): boolean {
  return id.startsWith("emp_") || id.startsWith("seed_");
}

function parsePaths(raw: string): string[] {
  try {
    const v = JSON.parse(raw);
    return Array.isArray(v) ? v.map(String) : [];
  } catch {
    return [];
  }
}

function fromRow(row: EmployeeRowDto): Employee {
  const agentRoleId = resolveLegacyAgencyRoleId(row.agentRoleId || "");
  return {
    id: row.id,
    employeeNo: row.employeeNo || "",
    name: row.name,
    age: typeof row.age === "number" && row.age > 0 ? row.age : 28,
    role: row.role || "员工",
    avatarId: row.avatarId || "classic",
    deskIndex: row.deskIndex ?? null,
    status: (row.status as EmployeeStatus) || "idle",
    createdAt: row.createdAt,
    workspaceRoot: row.workspaceRoot ?? null,
    readExtraPaths: parsePaths(row.readExtraPaths || "[]"),
    allowNetworkExfil: row.allowNetworkExfil === true,
    driveMode: row.driveMode === "sdk" || row.driveMode === "input_control" ? row.driveMode : "off",
    gender: row.gender === "female" ? "female" : "male",
    roleKind: row.roleKind === "reviewer" || row.roleKind === "boss" ? row.roleKind : "worker",
    brainSlot:
      row.brainSlot === "command" || row.brainSlot === "code" ? row.brainSlot : "work",
    outfit: row.outfit || "casual",
    hairStyle: row.hairStyle || (row.gender === "female" ? "bob" : "short"),
    agentRoleId,
    aiModel: row.aiModel || "",
    aiBaseUrl: row.aiBaseUrl || "",
    aiVisionModel: row.aiVisionModel || "",
    apiSource:
      row.apiSource === "local" || row.apiSource === "remote" ? row.apiSource : "inherit",
    remotePresetId: row.remotePresetId || "",
    codeEditorSurface: normalizeCodeEditorSurface(row.codeEditorSurface),
    ...(() => {
      const bind = loadRoleVoiceBind(row.id);
      const byRole = agentRoleId ? loadRoleVoiceBind(agentRoleId) : {};
      return {
        voiceToneId: bind.voiceToneId || byRole.voiceToneId,
        ttsProviderHint: bind.ttsProviderHint || byRole.ttsProviderHint,
      };
    })(),
  };
}

function normalizeCodeEditorSurface(raw: unknown): CodeEditorSurface {
  const s = String(raw || "inherit");
  if (s === "builtin" || s === "external") return s;
  return "inherit";
}

function resolveEmpPolicySurface(emp: Employee): "builtin" | "external" {
  if (emp.codeEditorSurface === "builtin" || emp.codeEditorSurface === "external") {
    return emp.codeEditorSurface;
  }
  return readCodingSurfacePrefs().defaultSurface;
}

function toRow(emp: Employee): EmployeeRowDto {
  return {
    id: emp.id,
    name: emp.name,
    role: emp.role,
    avatarId: emp.avatarId,
    deskIndex: emp.deskIndex,
    status: emp.status,
    createdAt: emp.createdAt,
    workspaceRoot: emp.workspaceRoot,
    readExtraPaths: JSON.stringify(emp.readExtraPaths ?? []),
    allowNetworkExfil: emp.allowNetworkExfil,
    driveMode: emp.driveMode,
    gender: emp.gender,
    roleKind: emp.roleKind,
    brainSlot: emp.brainSlot,
    outfit: emp.outfit || "casual",
    hairStyle: emp.hairStyle || "short",
    agentRoleId: emp.agentRoleId || "",
    aiModel: emp.aiModel || "",
    aiBaseUrl: emp.aiBaseUrl || "",
    aiVisionModel: emp.aiVisionModel || "",
    employeeNo: emp.employeeNo || "",
    apiSource: emp.apiSource || "inherit",
    remotePresetId: emp.remotePresetId || "",
    age: emp.age,
    codeEditorSurface: emp.codeEditorSurface || "inherit",
  };
}

function normalizeLocal(raw: Partial<Employee> & { id: string; name: string }): Employee {
  return {
    id: raw.id,
    employeeNo: raw.employeeNo || "",
    name: raw.name,
    age: typeof raw.age === "number" && raw.age > 0 ? raw.age : 28,
    role: raw.role || "员工",
    avatarId: raw.avatarId || "classic",
    deskIndex: raw.deskIndex ?? null,
    status: raw.status ?? "idle",
    createdAt: raw.createdAt ?? Date.now(),
    workspaceRoot: raw.workspaceRoot ?? null,
    readExtraPaths: Array.isArray(raw.readExtraPaths) ? raw.readExtraPaths : [],
    allowNetworkExfil: raw.allowNetworkExfil === true,
    driveMode: raw.driveMode === "sdk" || raw.driveMode === "input_control" ? raw.driveMode : "off",
    gender: raw.gender === "female" ? "female" : "male",
    roleKind: raw.roleKind === "reviewer" || raw.roleKind === "boss" ? raw.roleKind : "worker",
    brainSlot: raw.brainSlot === "command" || raw.brainSlot === "code" ? raw.brainSlot : "work",
    outfit: raw.outfit || "casual",
    hairStyle: raw.hairStyle || (raw.gender === "female" ? "bob" : "short"),
    agentRoleId: resolveLegacyAgencyRoleId(raw.agentRoleId || ""),
    aiModel: raw.aiModel || "",
    aiBaseUrl: raw.aiBaseUrl || "",
    aiVisionModel: raw.aiVisionModel || "",
    apiSource:
      raw.apiSource === "local" || raw.apiSource === "remote" ? raw.apiSource : "inherit",
    remotePresetId: raw.remotePresetId || "",
    codeEditorSurface: normalizeCodeEditorSurface(raw.codeEditorSurface),
  };
}

function readLocalStorageEmployees(): Employee[] {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return [];
    return parsed
      .filter((e): e is Partial<Employee> & { id: string; name: string } =>
        Boolean(e && typeof e === "object" && typeof (e as Employee).id === "string" && typeof (e as Employee).name === "string"),
      )
      .map(normalizeLocal);
  } catch {
    return [];
  }
}

async function remapProjectEmployeeIds(idMap: Record<string, string>): Promise<void> {
  try {
    const raw = await invoke<string | null>("xu_get_setting", { key: PROJECTS_DB_KEY });
    if (!raw) return;
    const list = JSON.parse(raw) as Array<{ employeeIds?: string[] }>;
    if (!Array.isArray(list)) return;
    let changed = false;
    for (const p of list) {
      if (!Array.isArray(p.employeeIds)) continue;
      const next = p.employeeIds.map((id) => idMap[id] || id);
      if (JSON.stringify(next) !== JSON.stringify(p.employeeIds)) {
        p.employeeIds = next;
        changed = true;
      }
    }
    if (changed) {
      await invoke("xu_set_setting", { key: PROJECTS_DB_KEY, value: JSON.stringify(list) });
    }
  } catch {
    /* ignore */
  }
}

async function migrateEmployeesSchema(rows: Employee[]): Promise<Employee[]> {
  const idMap: Record<string, string> = {};
  const patches: Employee[] = [];

  for (const emp of rows) {
    let next = { ...emp };
    let dirty = false;

    if (needsLegacyIdMigration(emp.id)) {
      const newId = nextSnowflakeId();
      idMap[emp.id] = newId;
      await invoke("xu_remap_employee_id", { oldId: emp.id, newId });
      next.id = newId;
      dirty = true;
    }

    const resolvedRole = resolveLegacyAgencyRoleId(emp.agentRoleId);
    if (resolvedRole !== emp.agentRoleId) {
      next.agentRoleId = resolvedRole;
      dirty = true;
    }

    if (!next.employeeNo?.trim()) {
      next.employeeNo = await nextEmployeeNo();
      dirty = true;
    }

    const needsPersona =
      !next.age ||
      next.age < 18 ||
      looksAutoGeneratedName(next.name) ||
      ["助手", "工程师", "导师", "审码"].includes(next.name) ||
      (next.role.trim() && next.name.trim() === next.role.trim());
    if (needsPersona) {
      const persona = generateVirtualPersona({
        roleKind: next.roleKind,
        seed: `${next.id}:${next.employeeNo}`,
      });
      next.name = persona.name;
      next.gender = persona.gender;
      next.age = persona.age;
      dirty = true;
    }

    if (dirty) {
      await invoke("xu_upsert_employee", { employee: toRow(next) });
      patches.push(next);
    } else {
      patches.push(next);
    }
  }

  if (Object.keys(idMap).length > 0) {
    await remapProjectEmployeeIds(idMap);
  }

  const fresh = await invoke<EmployeeRowDto[]>("xu_list_employees");
  return fresh.map(fromRow);
}

/** 姓名误存为岗位名时，补全虚构中文名（职务 · 姓名 展示） */
async function repairEmployeesWithRoleAsName(list: Employee[]): Promise<Employee[]> {
  const fixes: Employee[] = [];
  for (const emp of list) {
    const role = emp.role.trim();
    const name = emp.name.trim();
    if (!role || name !== role) continue;
    const persona = generateVirtualPersona({
      gender: emp.gender,
      roleKind: emp.roleKind,
      seed: `${emp.id}:${emp.employeeNo}:display-name`,
    });
    fixes.push({
      ...emp,
      name: persona.name,
      age: emp.age > 0 ? emp.age : persona.age,
    });
  }
  if (!fixes.length) return list;
  if (fixes.length === 1) {
    await invoke("xu_upsert_employee", { employee: toRow(fixes[0]) });
  } else {
    await invoke("xu_upsert_employees_batch", { employees: fixes.map(toRow) });
  }
  const fresh = await invoke<EmployeeRowDto[]>("xu_list_employees");
  const next = fresh.map(fromRow);
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
  return next;
}

async function runEmployeeMigrationsOnce(rows: Employee[]): Promise<Employee[]> {
  try {
    const done = await invoke<string | null>("xu_get_setting", { key: MIGRATION_KEY });
    if (done === "1") {
      return rows.map((e) => {
        const agentRoleId = resolveLegacyAgencyRoleId(e.agentRoleId);
        return agentRoleId === e.agentRoleId ? e : { ...e, agentRoleId };
      });
    }
    const migrated = await migrateEmployeesSchema(rows);
    await invoke("xu_set_setting", { key: MIGRATION_KEY, value: "1" });
    return migrated;
  } catch {
    return rows;
  }
}

export function getAvatar(avatarId: string): AvatarStyle {
  return AVATAR_STYLES.find((a) => a.id === avatarId) ?? AVATAR_STYLES[0];
}

export async function bootstrapEmployees(): Promise<Employee[]> {
  const local = readLocalStorageEmployees();
  let rows = await invoke<EmployeeRowDto[]>("xu_bootstrap_employees", {
    payload: {
      employees: local.map(toRow),
      seedIfEmpty: true,
    },
  });
  cache = await runEmployeeMigrationsOnce(rows.map(fromRow));
  cache = await repairEmployeesWithRoleAsName(cache);
  bootstrapped = true;
  if (local.length > 0) {
    try {
      localStorage.removeItem(STORAGE_KEY);
    } catch {
      /* ignore */
    }
  }
  try {
    if (!sessionStorage.getItem("xu.coldStart.busyReset")) {
      const summary = await invoke<{
        scanned: number;
        resumed: number;
        meeting: number;
        skipped: number;
        errors: string[];
      }>("xu_resume_interrupted_dispatches", { maxResume: 6 });
      sessionStorage.setItem("xu.coldStart.busyReset", "1");
      const fresh = await invoke<EmployeeRowDto[]>("xu_list_employees");
      cache = fresh.map(fromRow);
      if ((summary.resumed ?? 0) > 0 || (summary.meeting ?? 0) > 0) {
        console.info("[xu] resume interrupted dispatches", summary);
      }
    }
  } catch (e) {
    console.warn("[xu] resume interrupted dispatches failed", e);
  }
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
  return cache;
}

export async function loadEmployees(): Promise<Employee[]> {
  if (!bootstrapped) return bootstrapEmployees();
  const rows = await invoke<EmployeeRowDto[]>("xu_list_employees");
  cache = await repairEmployeesWithRoleAsName(rows.map(fromRow));
  return cache;
}

export function readEmployees(): Employee[] {
  return cache;
}

export async function saveEmployee(emp: Employee): Promise<void> {
  await invoke("xu_upsert_employee", { employee: toRow(emp) });
  if (emp.voiceToneId || emp.ttsProviderHint) {
    saveRoleVoiceBind(emp.id, {
      voiceToneId: emp.voiceToneId,
      ttsProviderHint: emp.ttsProviderHint ?? "auto",
    });
    if (emp.agentRoleId) {
      saveRoleVoiceBind(emp.agentRoleId, {
        voiceToneId: emp.voiceToneId,
        ttsProviderHint: emp.ttsProviderHint ?? "auto",
      });
    }
  }
  await loadEmployees();
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
}

export async function saveEmployeesBatch(emps: Employee[]): Promise<void> {
  if (!emps.length) return;
  const prevById = new Map(cache.map((e) => [e.id, toRow(e)]));
  const dirty: Employee[] = [];
  for (const emp of emps) {
    const row = toRow(emp);
    const prev = prevById.get(emp.id);
    if (!prev || JSON.stringify(prev) !== JSON.stringify(row)) {
      dirty.push(emp);
    }
  }
  if (!dirty.length) return;
  if (dirty.length === 1) {
    await invoke("xu_upsert_employee", { employee: toRow(dirty[0]) });
  } else {
    await invoke("xu_upsert_employees_batch", {
      employees: dirty.map(toRow),
    });
  }
  await loadEmployees();
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
}

export function findEmployeeByAgentRoleId(
  roleId: string,
  employees = readEmployees(),
): Employee | undefined {
  const key = resolveLegacyAgencyRoleId(roleId);
  if (!key) return undefined;
  return employees.find((e) => resolveLegacyAgencyRoleId(e.agentRoleId) === key);
}

const ensureRoleLocks = new Map<string, Promise<Employee>>();

/** Create (or reuse) an employee for an agency catalog role. */
export async function ensureEmployeeForRole(
  role: import("../office/agencyRoles").AgencyRole,
): Promise<Employee> {
  const roleKey = resolveLegacyAgencyRoleId(role.id);
  const pending = ensureRoleLocks.get(roleKey);
  if (pending) return pending;

  const job = (async () => {
    await loadEmployees();
    const existing = findEmployeeByAgentRoleId(role.id);
    if (existing) return existing;
    const gender: Gender = /女|design|ux|content|marketing/i.test(`${role.nameZh}${role.id}`)
      ? "female"
      : "male";
    return addEmployee({
      role: role.nameZh || role.name,
      agentRoleId: role.id,
      roleKind: role.roleKind,
      brainSlot: role.brainSlot,
      gender,
      avatarId: gender === "female" ? "rose" : "classic",
      deskIndex: null,
      workspaceRoot: null,
      readExtraPaths: [],
      allowNetworkExfil: false,
      driveMode: "off",
      apiSource: "inherit",
    });
  })();

  ensureRoleLocks.set(roleKey, job);
  try {
    return await job;
  } finally {
    ensureRoleLocks.delete(roleKey);
  }
}

/** Ensure roster covers matched agency roles; returns employees in role-id order. */
export async function ensureEmployeesForRoleIds(roleIds: string[]): Promise<Employee[]> {
  const { ensureAgencyCatalog, getAgencyRole } = await import("../office/agencyRoles");
  await ensureAgencyCatalog();
  const out: Employee[] = [];
  const seen = new Set<string>();
  for (const rid of roleIds) {
    const role = getAgencyRole(rid);
    if (!role || role.roleKind === "boss") continue;
    const emp = await ensureEmployeeForRole(role);
    if (seen.has(emp.id)) continue;
    seen.add(emp.id);
    out.push(emp);
  }
  return out;
}

export async function addEmployee(input: EmployeeInput): Promise<Employee> {
  const roleKind = input.roleKind ?? "worker";
  const persona: VirtualPersona = generateVirtualPersona({
    gender: input.gender,
    roleKind,
    seed: nextSnowflakeId(),
  });
  const emp: Employee = {
    id: nextSnowflakeId(),
    employeeNo: input.employeeNo?.trim() || (await nextEmployeeNo()),
    name: (input.name || "").trim() || persona.name,
    age: input.age && input.age > 0 ? input.age : persona.age,
    role: input.role.trim() || "员工",
    avatarId: input.avatarId || "classic",
    deskIndex: input.deskIndex,
    status: "idle",
    createdAt: Date.now(),
    workspaceRoot: input.workspaceRoot ?? null,
    readExtraPaths: input.readExtraPaths ?? [],
    allowNetworkExfil: input.allowNetworkExfil === true,
    driveMode: input.driveMode ?? "off",
    gender: input.gender ?? persona.gender,
    roleKind,
    brainSlot: input.brainSlot ?? "work",
    outfit: input.outfit ?? "casual",
    hairStyle: input.hairStyle ?? ((input.gender ?? persona.gender) === "female" ? "bob" : "short"),
    agentRoleId: resolveLegacyAgencyRoleId(input.agentRoleId ?? ""),
    aiModel: (input.aiModel ?? "").trim(),
    aiBaseUrl: (input.aiBaseUrl ?? "").trim(),
    aiVisionModel: (input.aiVisionModel ?? "").trim(),
    apiSource:
      input.apiSource === "local" || input.apiSource === "remote" ? input.apiSource : "inherit",
    remotePresetId: (input.remotePresetId ?? "").trim(),
    codeEditorSurface: normalizeCodeEditorSurface(input.codeEditorSurface ?? "inherit"),
  };
  await saveEmployee(emp);
  return emp;
}

const EMPLOYEE_NO_SEQ_KEY = "xu.employee_no_seq";

export async function nextEmployeeNo(): Promise<string> {
  let seq = 1;
  try {
    const raw = await invoke<string | null>("xu_get_setting", { key: EMPLOYEE_NO_SEQ_KEY });
    if (raw != null && raw !== "") {
      const n = Number(raw);
      if (Number.isFinite(n) && n >= 0) seq = Math.floor(n) + 1;
    }
  } catch {
    try {
      const local = Number(localStorage.getItem(EMPLOYEE_NO_SEQ_KEY) || "0");
      if (Number.isFinite(local) && local >= 0) seq = Math.floor(local) + 1;
    } catch {
      /* ignore */
    }
  }
  try {
    await invoke("xu_set_setting", { key: EMPLOYEE_NO_SEQ_KEY, value: String(seq) });
  } catch {
    try {
      localStorage.setItem(EMPLOYEE_NO_SEQ_KEY, String(seq));
    } catch {
      /* ignore */
    }
  }
  return `F${String(seq).padStart(4, "0")}`;
}

export async function updateEmployee(id: string, patch: Partial<Employee>): Promise<void> {
  const cur = cache.find((e) => e.id === id);
  if (!cur) return;
  await saveEmployee({ ...cur, ...patch, id, name: patch.name ?? cur.name });
}

export async function removeEmployee(id: string): Promise<void> {
  await invoke("xu_delete_employee", { id });
  await loadEmployees();
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
}

export function nextFreeDeskIndex(deskCount: number, employees = readEmployees()): number | null {
  const used = new Set(employees.map((e) => e.deskIndex).filter((n): n is number => n != null));
  for (let i = 0; i < deskCount; i++) {
    if (!used.has(i)) return i;
  }
  return null;
}

export function listOccupiedDeskIndices(employees = readEmployees()): number[] {
  return [
    ...new Set(employees.map((e) => e.deskIndex).filter((n): n is number => n != null)),
  ].sort((a, b) => a - b);
}

export async function unbindEmployeesFromDesks(indices: number[]): Promise<number> {
  const set = new Set(indices.filter((n) => Number.isFinite(n)));
  if (set.size === 0) return 0;
  const affected = cache.filter((e) => e.deskIndex != null && set.has(e.deskIndex));
  if (affected.length === 0) return 0;
  for (const emp of affected) {
    await invoke("xu_upsert_employee", { employee: toRow({ ...emp, deskIndex: null }) });
  }
  await loadEmployees();
  window.dispatchEvent(new CustomEvent("xu-employees-changed"));
  return affected.length;
}

export async function buildPolicyPreamble(emp: Employee, taskHint?: string): Promise<string> {
  const writeRoot = emp.workspaceRoot?.trim() || "(未设置)";
  const readExtra =
    emp.readExtraPaths.filter(Boolean).length > 0
      ? emp.readExtraPaths.filter(Boolean).map((p) => `- ${p}`).join("\n")
      : "- （无额外只读路径）";
  const exfil = emp.allowNetworkExfil
    ? "允许在完成任务必要时使用网络；仍禁止泄露密钥/凭据。"
    : "禁止将工作区内源码、机密或文件内容上传/粘贴到外网、公开聊天或无关服务（禁外传）。";
  const agency = getAgencyRole(emp.agentRoleId);
  let agencyBlock = "";
  if (agency) {
    const prompt = await ensureAgencyRolePrompt(agency.id);
    const personaRole = { ...agency, prompt };
    agencyBlock = `\n【Agency 短人设 · ${personaRole.nameZh || personaRole.name}】\n${buildAgencyShortPersona(personaRole, { task: taskHint || "" })}\n`;
    const pack = buildRoleAgencyPack(agency);
    if (pack) agencyBlock += `\n${pack}\n`;
    try {
      const { buildEmployeeCurriculumHint } = await import("../training/employeeHints");
      const cur = await buildEmployeeCurriculumHint(agency.id, emp.id);
      if (cur) agencyBlock += `\n${cur}\n`;
    } catch {
      /* ignore */
    }
  }

  const { buildOralPersonaBlock } = await import("./assistantOralPersona");
  agencyBlock += buildOralPersonaBlock();

  return [
    `【虚募阁员工策略 · ${emp.name} · 策略约束非 OS 沙箱】`,
    `你是「${emp.name}」（职责：${emp.role}，角色：${emp.roleKind}，脑槽：${emp.brainSlot}）。必须遵守：`,
    `1. 可写范围：仅可在以下目录内创建/编辑/删除文件：${writeRoot}`,
    `2. 只读范围：工作区以外默认只读；额外只读路径：`,
    readExtra,
    `3. 外传：${exfil}`,
    `4. 不得修改工作区外的系统配置、全局密钥或无关仓库。`,
    `5. 若任务需要越界，先说明原因并停止，等待 Boss 放宽边界。`,
    ideOpenPolicyLine(resolveEmpPolicySurface(emp)),
    agencyBlock,
    `【任务】`,
  ]
    .filter((s) => s !== "")
    .join("\n");
}

export async function composeEmployeeTaskMessage(
  emp: Employee,
  task: string,
  extraHints?: string,
): Promise<string> {
  const t = task.trim();
  const base = `${await buildPolicyPreamble(emp, t)}\n${t}`;
  const hints = extraHints?.trim();
  return hints ? `${base}\n\n${hints}` : base;
}

export function employeeBoundarySummary(emp: Employee): string {
  if (!emp.workspaceRoot) return "未设置工作区（不可派活）";
  const exfil = emp.allowNetworkExfil ? "可外传" : "禁外传";
  return `写：${emp.workspaceRoot} · ${exfil} · ${emp.brainSlot}`;
}

export { generateVirtualPersona, isSnowflakeId };

export async function appendFouMessage(input: {
  sessionTag: string;
  employeeId?: string | null;
  role: string;
  content: string;
  imagePath?: string | null;
}): Promise<void> {
  try {
    await invoke("xu_append_message", {
      message: {
        id: nextSnowflakeId(),
        sessionTag: input.sessionTag,
        employeeId: input.employeeId ?? null,
        role: input.role,
        content: input.content,
        imagePath: input.imagePath ?? null,
        createdAt: Date.now(),
      },
    });
  } catch (e) {
    console.warn("appendFouMessage failed", e);
  }
}

export async function getChatRetentionDays(): Promise<number> {
  try {
    return await invoke<number>("xu_get_retention_days");
  } catch {
    return 0;
  }
}

export async function setChatRetentionDays(days: number): Promise<void> {
  await invoke("xu_set_retention_days", { days: Math.max(0, Math.floor(days)) });
}

export async function getDefaultReviewerId(): Promise<string | null> {
  try {
    return await invoke<string | null>("xu_get_default_reviewer_id");
  } catch {
    return null;
  }
}

export async function setDefaultReviewerId(id: string | null): Promise<void> {
  await invoke("xu_set_default_reviewer_id", { id });
}
