/**
 * Fictional employee persona generator (name / gender / age).
 * For UI immersion only — not real personal data.
 */
import type { Gender, RoleKind } from "./employees";

const SURNAMES = [
  "王", "李", "张", "刘", "陈", "杨", "赵", "黄", "周", "吴",
  "徐", "孙", "胡", "朱", "高", "林", "何", "郭", "马", "罗",
  "梁", "宋", "郑", "谢", "韩", "唐", "冯", "于", "董", "萧",
];

const MALE_NAMES = [
  "伟", "强", "磊", "洋", "勇", "军", "杰", "涛", "明", "超",
  "秀英", "建华", "志强", "浩然", "子轩", "宇航", "博文", "俊杰", "嘉诚", "一鸣",
];

const FEMALE_NAMES = [
  "芳", "娜", "敏", "静", "丽", "艳", "娟", "秀英", "婷", "雪",
  "梦瑶", "欣怡", "梓涵", "雨萱", "思琪", "佳怡", "诗涵", "可欣", "语嫣", "若曦",
];

function hashSeed(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function pick<T>(arr: T[], seed: string, salt: string): T {
  const h = hashSeed(`${seed}:${salt}`);
  return arr[h % arr.length];
}

function ageRange(roleKind: RoleKind): [number, number] {
  if (roleKind === "boss") return [35, 55];
  if (roleKind === "reviewer") return [30, 48];
  return [22, 38];
}

export type VirtualPersona = {
  name: string;
  gender: Gender;
  age: number;
};

export function generateVirtualPersona(opts?: {
  gender?: Gender;
  roleKind?: RoleKind;
  seed?: string;
}): VirtualPersona {
  const seed = opts?.seed || `${Date.now()}_${Math.random()}`;
  const roleKind = opts?.roleKind || "worker";
  let gender = opts?.gender;
  if (!gender) {
    gender = pick(["male", "female"] as Gender[], seed, "gender");
  }
  const surname = pick(SURNAMES, seed, "surname");
  const given = pick(gender === "female" ? FEMALE_NAMES : MALE_NAMES, seed, "given");
  const name = `${surname}${given}`;
  const [min, max] = ageRange(roleKind);
  const span = max - min + 1;
  const age = min + (hashSeed(`${seed}:age`) % span);
  return { name, gender, age };
}

/** True when name looks auto-generated from role title + index. */
export function looksAutoGeneratedName(name: string): boolean {
  return /\d+$/.test(name.trim()) && name.length <= 12;
}
